[package]
name = "simple-blockchain"
version = "0.1.0"
edition = "2021"

[lib]
name = "blockchainlib"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
sha2 = "0.9.8"
